%%
clc;
clear all;
close all;

fs=1000;
path = { '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_1.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_2.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_3.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_4.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_5.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_6.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_7.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_8.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_9.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_10.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_11.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_12.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_13.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_14.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_15.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_16.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_17.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_18.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_19.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_20.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_21.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_22.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_23.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_24.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_25.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_26.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_27.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_28.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_29.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_30.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_31.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_32.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_33.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_34.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_35.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_36.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_37.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_38.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_39.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_40.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_41.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_42.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_43.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_44.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_45.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_46.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_47.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_48.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_49.wav'...
         '/Users/mac/Desktop/sp_cup/final/practc data/Practice_dataset/Practice_dataset/Practice_50.wav'...
         };
    
    
 files = {'PP1','PP2','PP3','PP4','PP5','PP6','PP7','PP8','PP9',...
          'PP10','PP11','PP12','PP13','PP14','PP15','PP16','PP17','PP18','PP19',...
          'PP20','PP21','PP22','PP23','PP24','PP25','PP26','PP27','PP28','PP29'...
          'PP30','PP31','PP32','PP33','PP34','PP35','PP36','PP37','PP38','PP39'...
          'PP40','PP41','PP42','PP43','PP44','PP45','PP46','PP47','PP48','PP49','PP50'...
          };
         
    len = length(files);
    
    
 %%   
for jl = 1:len
    
    
    %%listing features
    var_x = [];
    mean_x = [];
    diff_x = [];
    wav_coef = [];
    wavcoef_n = [];
    range = [];
    AR_coef=[];
    
    
    pp=1; %initialization for wav_coef loop
    
%     if jl < 94
%         ENF_file = ['P_' num2str(jl)];
%     else
%         ENF_file = ['A_' num2str(jl-93)];
%     end
%     
%     fprintf('loading data from ....%s/n',ENF_file);
%     fprintf('recording no.  ---> %d/n',jl);
%    
%     load(ENF_file);

    fprintf('loading data from ....%s\n',char(path(jl)));
    fprintf('recording no.  ---> %d\n',jl);

    enf_win = 32;       %enf window
    win_time = 2;
    [F, sig, freq] = enf_extract_from_audio_and_power(char(path(jl)),win_time);
    save(['enf_' num2str(jl)],'F');
    %plot(F)
    x = F;

    %% Statistical feature
    

    for i = 2:enf_win:(length(x)-enf_win)        %window length enf_win samples
            
        m = mean(x(i:i+enf_win - 1));        %taking mean of enf_win samples at a time
        mean_x = [mean_x m];        %appending window mean to matrix

        v = log(var(x(i:i+enf_win - 1)));         %taking variance of enf_win samples at a time

        var_x = [var_x v];          %appending window variance to matrix

    end
    

    
    for i = 2:enf_win:(length(x)-enf_win)        %window length enf_win samples 

        d_m = abs(diff(x(i:i+enf_win - 1))); %make a difference matrix

        d1 = sort(d_m,'descend');
        
        d = (d1(1)+d1(2)+d1(3))/3;           %taking mean of max 3 differences

        diff_x = [diff_x d];

    end


   %% Wavelet based features

   F1=F/max(F);                         %normalize ENF
   
   feature_per_rcrd = 0;
   
   
    for i = 2:enf_win:(length(F)-enf_win)
       
       temp1= F(i:i+enf_win - 1);
       temp2=F1(i:i+enf_win - 1);                  % for normalized ENF

       AR=ar(temp1,2);           %2nd order Autoregressive model
       bb=AR.a(2:3);
       
       AR_coef(:,pp)=bb;
       
       [C, L]=wavedec(temp1,5,'haar');

       [C1, L1]=wavedec(temp2,5,'haar');      % for normalized ENF

        wav_coef(:,pp)=C;
        
        wavcoef_n(:,pp)=C1;
        
       rn = log(max(temp1)-min(temp1));   % take range of ENF
       range = [range rn];
       
        pp=pp+1;
        feature_per_rcrd = feature_per_rcrd + 1;

    end
    
    

%%
%arranging training dataset 

    master_trainer = [ var_x' mean_x' diff_x' .....
                       AR_coef' wav_coef' range'];

    save([char(files(jl)) '_' num2str(win_time*1000)],'master_trainer','var_x','mean_x',...
                         'diff_x', 'AR_coef', 'wav_coef', ...
                         'range', 'wavcoef_n','sig','freq');
end